import type { OpportunityLane, Reliability } from "@/types/opportunity";

export type SaiFirstGenRelevance = "high" | "moderate" | "low";

export type SaiReliability = Reliability | "verified-live" | "verify-url";

export type SaiOpportunity = {
  id: string;
  title: string;
  lane: OpportunityLane;
  url: string;
  region: string;
  ageRange: string[];
  primaryCommunities: string[];
  secondaryCommunities: string[];
  openToAll: boolean;
  interests: string[];
  supportTypes: string[];
  firstGenRelevance: SaiFirstGenRelevance;
  description: string;
  whyItMayFit: string;
  reliability: SaiReliability;
  badges: string[];
};

/** Sai research pass — additional STEM opportunities for Student Nova */
export const ADDITIONAL_OPPORTUNITIES: SaiOpportunity[] = [
  {
    id: "fin-hfsv",
    title: "Hispanic Foundation of Silicon Valley",
    lane: "financial",
    url: "https://www.hfsv.org/",
    region: "Bay Area (Silicon Valley)",
    ageRange: ["16–17", "18–24"],
    primaryCommunities: ["Latinx / Hispanic"],
    secondaryCommunities: ["Low-income", "Underrepresented"],
    openToAll: false,
    interests: ["Computer Science", "Engineering", "AI / Data", "Biology / Health"],
    supportTypes: ["Scholarships", "Community"],
    firstGenRelevance: "high",
    description:
      "Silicon Valley foundation advancing Latinx success, including scholarships and a STEM pipeline.",
    whyItMayFit: "May be relevant for Latinx Bay Area students seeking local scholarships and community.",
    reliability: "verified-live",
    badges: ["First-gen friendly", "Bay Area", "Scholarship"],
  },
  {
    id: "fin-ten-thousand-degrees",
    title: "10,000 Degrees",
    lane: "financial",
    url: "https://10000degrees.org/",
    region: "Bay Area (Marin & expanding)",
    ageRange: ["16–17", "18–24"],
    primaryCommunities: [],
    secondaryCommunities: ["Underrepresented", "Low-income", "Latinx / Hispanic"],
    openToAll: false,
    interests: ["Computer Science", "Engineering", "AI / Data", "Unsure, help me explore"],
    supportTypes: ["Scholarships", "Mentorship", "Community"],
    firstGenRelevance: "high",
    description:
      "Provides scholarships and one-on-one advising to first-gen, low-income students through graduation.",
    whyItMayFit: "May be relevant for first-gen Bay Area students needing both funding and guidance.",
    reliability: "verified-live",
    badges: ["First-gen friendly", "Bay Area", "Scholarship"],
  },
  {
    id: "fin-tillman",
    title: "Pat Tillman Foundation — Tillman Scholars",
    lane: "financial",
    url: "https://pattillmanfoundation.org/",
    region: "National (serves Bay Area)",
    ageRange: ["18–24", "25+"],
    primaryCommunities: ["Veteran / military-connected"],
    secondaryCommunities: [],
    openToAll: false,
    interests: ["Computer Science", "Engineering", "AI / Data", "Biology / Health"],
    supportTypes: ["Scholarships", "Mentorship", "Community"],
    firstGenRelevance: "moderate",
    description: "Scholarship and leadership program for service members, veterans, and military spouses.",
    whyItMayFit:
      "May be relevant for military-connected students pursuing STEM with leadership support.",
    reliability: "verified-live",
    badges: ["Veteran", "Scholarship", "Mentorship"],
  },
  {
    id: "fin-aicf",
    title: "American Indian College Fund",
    lane: "financial",
    url: "https://collegefund.org/",
    region: "National (serves Bay Area)",
    ageRange: ["16–17", "18–24", "25+"],
    primaryCommunities: ["Native American / Indigenous"],
    secondaryCommunities: ["Low-income", "Underrepresented"],
    openToAll: false,
    interests: ["Engineering", "Computer Science", "AI / Data", "Biology / Health"],
    supportTypes: ["Scholarships", "Community"],
    firstGenRelevance: "high",
    description:
      "Largest provider of scholarships and support to Native American students, including STEM.",
    whyItMayFit: "May be relevant for Native/Indigenous students seeking scholarships in STEM fields.",
    reliability: "verified-live",
    badges: ["First-gen friendly", "Scholarship"],
  },
  {
    id: "fin-cobell",
    title: "Cobell Scholarship",
    lane: "financial",
    url: "https://cobellscholar.org/",
    region: "National (serves Bay Area)",
    ageRange: ["18–24", "25+"],
    primaryCommunities: ["Native American / Indigenous"],
    secondaryCommunities: [],
    openToAll: false,
    interests: ["Engineering", "Computer Science", "AI / Data", "Biology / Health"],
    supportTypes: ["Scholarships"],
    firstGenRelevance: "high",
    description:
      "Scholarship for enrolled members of US federally recognized tribes across all fields incl. STEM.",
    whyItMayFit:
      "May be relevant for enrolled tribal members; verify enrollment requirements on the official site.",
    reliability: "verified-live",
    badges: ["Scholarship"],
  },
  {
    id: "fin-apia",
    title: "APIA Scholars",
    lane: "financial",
    url: "https://apiascholars.org/",
    region: "National (serves Bay Area)",
    ageRange: ["16–17", "18–24"],
    primaryCommunities: [
      "Pacific Islander",
      "Asian / Asian American",
      "Filipino / Filipino American",
    ],
    secondaryCommunities: ["Low-income", "Underrepresented"],
    openToAll: false,
    interests: ["Computer Science", "Engineering", "AI / Data", "Biology / Health"],
    supportTypes: ["Scholarships", "Community"],
    firstGenRelevance: "high",
    description:
      "Scholarships for Asian & Pacific Islander Americans, with priority for first-gen and low-income; explicitly serves Filipino Americans.",
    whyItMayFit:
      "May be relevant for Filipino, Pacific Islander, and AAPI students, especially first-gen.",
    reliability: "verified-live",
    badges: ["First-gen friendly", "Scholarship"],
  },
  {
    id: "fin-uncf",
    title: "UNCF (United Negro College Fund)",
    lane: "financial",
    url: "https://uncf.org/",
    region: "National (serves Bay Area)",
    ageRange: ["16–17", "18–24"],
    primaryCommunities: ["Black / African American"],
    secondaryCommunities: ["Low-income", "Underrepresented"],
    openToAll: false,
    interests: ["Computer Science", "Engineering", "AI / Data", "Biology / Health"],
    supportTypes: ["Scholarships", "Community"],
    firstGenRelevance: "high",
    description: "Major provider of scholarships and STEM programs for Black students.",
    whyItMayFit: "May be relevant for Black students seeking scholarships and STEM-specific programs.",
    reliability: "verified-live",
    badges: ["First-gen friendly", "Scholarship"],
  },
  {
    id: "edu-codepath",
    title: "CodePath",
    lane: "educational",
    url: "https://www.codepath.org/",
    region: "National (Bay Area roots & partners)",
    ageRange: ["18–24"],
    primaryCommunities: [],
    secondaryCommunities: [
      "Underrepresented",
      "Low-income",
      "Black / African American",
      "Latinx / Hispanic",
    ],
    openToAll: false,
    interests: ["Computer Science", "AI / Data", "Cybersecurity"],
    supportTypes: ["Free workshops", "Mentorship", "Internships"],
    firstGenRelevance: "high",
    description:
      "Free, industry-designed CS courses, interview prep, and career support for underrepresented college students.",
    whyItMayFit: "May be relevant for first-gen CS students wanting free, job-focused training.",
    reliability: "verified-live",
    badges: ["First-gen friendly", "Free workshops", "Mentorship"],
  },
  {
    id: "edu-breakthrough-sv",
    title: "Breakthrough Silicon Valley",
    lane: "educational",
    url: "https://breakthroughsv.org/",
    region: "Bay Area (San Jose)",
    ageRange: ["Under 16", "16–17", "18–24"],
    primaryCommunities: [],
    secondaryCommunities: [
      "Underrepresented",
      "Low-income",
      "Latinx / Hispanic",
      "Asian / Asian American",
    ],
    openToAll: false,
    interests: ["Computer Science", "Engineering", "AI / Data", "Unsure, help me explore"],
    supportTypes: ["Free workshops", "Mentorship", "Community"],
    firstGenRelevance: "high",
    description: "Guides first-gen students from middle school to college with academic and STEM support.",
    whyItMayFit: "May be relevant for younger first-gen Bay Area students building a STEM path.",
    reliability: "verified-live",
    badges: ["First-gen friendly", "Bay Area", "Free workshops"],
  },
  {
    id: "edu-code-nation",
    title: "Code Nation",
    lane: "educational",
    url: "https://codenation.org/",
    region: "National (Bay Area programs)",
    ageRange: ["16–17"],
    primaryCommunities: [],
    secondaryCommunities: [
      "Underrepresented",
      "Low-income",
      "Black / African American",
      "Latinx / Hispanic",
    ],
    openToAll: false,
    interests: ["Computer Science", "AI / Data", "Design / Product"],
    supportTypes: ["Free workshops", "Mentorship", "Community"],
    firstGenRelevance: "high",
    description:
      "Free coding courses for students in under-resourced high schools, taught with industry volunteers.",
    whyItMayFit:
      "May be relevant for Bay Area high schoolers seeking free coding instruction and mentors.",
    reliability: "verified-live",
    badges: ["First-gen friendly", "Free workshops", "Mentorship"],
  },
  {
    id: "edu-vetsintech",
    title: "VetsinTech",
    lane: "educational",
    url: "https://vetsintech.co/",
    region: "National (San Francisco-founded)",
    ageRange: ["18–24", "25+"],
    primaryCommunities: ["Veteran / military-connected"],
    secondaryCommunities: [],
    openToAll: false,
    interests: ["Computer Science", "AI / Data", "Cybersecurity", "Entrepreneurship"],
    supportTypes: ["Free workshops", "Internships", "Community", "Mentorship"],
    firstGenRelevance: "moderate",
    description: "Supports veterans entering tech with free training, hackathons, and employment programs.",
    whyItMayFit:
      "May be relevant for military-connected students transitioning into tech careers.",
    reliability: "verified-live",
    badges: ["Veteran", "Free workshops", "Bay Area"],
  },
  {
    id: "edu-aapd",
    title: "AAPD Summer Internship Program",
    lane: "educational",
    url: "https://www.aapd.com/",
    region: "National (serves Bay Area)",
    ageRange: ["18–24", "25+"],
    primaryCommunities: ["Disabled / neurodivergent"],
    secondaryCommunities: [],
    openToAll: false,
    interests: ["Computer Science", "AI / Data", "Engineering", "Entrepreneurship"],
    supportTypes: ["Internships", "Mentorship", "Community"],
    firstGenRelevance: "moderate",
    description: "Paid summer internships and mentorship for students and recent grads with disabilities.",
    whyItMayFit:
      "May be relevant for disabled/neurodivergent students seeking paid, supported experience.",
    reliability: "verified-live",
    badges: ["Internship", "Mentorship"],
  },
  {
    id: "pro-techqueria",
    title: "Techqueria",
    lane: "professional",
    url: "https://techqueria.org/",
    region: "Bay Area + national",
    ageRange: ["18–24", "25+"],
    primaryCommunities: ["Latinx / Hispanic"],
    secondaryCommunities: [],
    openToAll: false,
    interests: ["Computer Science", "AI / Data", "Design / Product", "Cybersecurity"],
    supportTypes: ["Community", "Mentorship"],
    firstGenRelevance: "moderate",
    description:
      "One of the largest communities of Latinx professionals in tech, with events and mentorship.",
    whyItMayFit: "May be relevant for Latinx students seeking a Bay Area tech community and mentors.",
    reliability: "verified-live",
    badges: ["Community", "Mentorship"],
  },
  {
    id: "pro-women-who-code",
    title: "Women Who Code",
    lane: "professional",
    url: "https://www.womenwhocode.com/",
    region: "National (Bay Area network)",
    ageRange: ["18–24", "25+"],
    primaryCommunities: ["Woman in STEM"],
    secondaryCommunities: [],
    openToAll: false,
    interests: ["Computer Science", "AI / Data", "Cybersecurity"],
    supportTypes: ["Community", "Mentorship"],
    firstGenRelevance: "low",
    description: "Global community supporting women and nonbinary people in technology careers.",
    whyItMayFit: "May be relevant for women/nonbinary students building a tech network.",
    reliability: "verified-live",
    badges: ["Community", "Mentorship", "Women in STEM"],
  },
  {
    id: "pro-anitab",
    title: "AnitaB.org (Grace Hopper Celebration)",
    lane: "professional",
    url: "https://anitab.org/",
    region: "National (serves Bay Area)",
    ageRange: ["18–24", "25+"],
    primaryCommunities: ["Woman in STEM"],
    secondaryCommunities: ["Underrepresented"],
    openToAll: false,
    interests: ["Computer Science", "AI / Data", "Engineering"],
    supportTypes: ["Community", "Mentorship", "Scholarships"],
    firstGenRelevance: "low",
    description:
      "Advances women in computing; runs the Grace Hopper Celebration and offers scholarships to attend.",
    whyItMayFit:
      "May be relevant for women in computing seeking community, conferences, and career growth.",
    reliability: "verified-live",
    badges: ["Community", "Mentorship", "Women in STEM"],
  },
  {
    id: "pro-beyond12",
    title: "Beyond 12",
    lane: "professional",
    url: "https://beyond12.org/",
    region: "Bay Area (Oakland) + national",
    ageRange: ["18–24"],
    primaryCommunities: [],
    secondaryCommunities: ["Underrepresented", "Low-income"],
    openToAll: false,
    interests: ["Computer Science", "Engineering", "AI / Data", "Unsure, help me explore"],
    supportTypes: ["Mentorship", "Community"],
    firstGenRelevance: "high",
    description: "Oakland-based org providing coaching to help first-gen students complete college.",
    whyItMayFit: "May be relevant for first-gen Bay Area college students wanting persistence support.",
    reliability: "verified-live",
    badges: ["First-gen friendly", "Bay Area", "Mentorship"],
  },
  {
    id: "pro-startout",
    title: "StartOut",
    lane: "professional",
    url: "https://startout.org/",
    region: "National (San Francisco-founded)",
    ageRange: ["18–24", "25+"],
    primaryCommunities: ["LGBTQ+"],
    secondaryCommunities: [],
    openToAll: false,
    interests: ["Entrepreneurship", "Computer Science", "AI / Data", "Design / Product"],
    supportTypes: ["Mentorship", "Community"],
    firstGenRelevance: "low",
    description: "Supports LGBTQ+ entrepreneurs and technologists with mentorship and networking.",
    whyItMayFit: "May be relevant for LGBTQ+ students interested in startups and tech leadership.",
    reliability: "verified-live",
    badges: ["Community", "Mentorship", "LGBTQ+"],
  },
  {
    id: "pro-o4u",
    title: "Out for Undergrad (O4U)",
    lane: "professional",
    url: "https://www.outforundergrad.org/",
    region: "National (serves Bay Area)",
    ageRange: ["18–24"],
    primaryCommunities: ["LGBTQ+"],
    secondaryCommunities: ["Underrepresented"],
    openToAll: false,
    interests: ["Computer Science", "AI / Data", "Engineering", "Design / Product"],
    supportTypes: ["Community", "Mentorship"],
    firstGenRelevance: "moderate",
    description:
      "Career development conferences (incl. Tech) helping high-achieving LGBTQ+ undergrads.",
    whyItMayFit:
      "May be relevant for LGBTQ+ undergrads seeking tech career development and networks.",
    reliability: "verified-live",
    badges: ["Community", "Mentorship", "LGBTQ+"],
  },
  {
    id: "pro-disability-in",
    title: "Disability:IN NextGen Leaders",
    lane: "professional",
    url: "https://disabilityin.org/",
    region: "National (serves Bay Area)",
    ageRange: ["18–24", "25+"],
    primaryCommunities: ["Disabled / neurodivergent"],
    secondaryCommunities: [],
    openToAll: false,
    interests: ["Computer Science", "AI / Data", "Engineering", "Entrepreneurship"],
    supportTypes: ["Mentorship", "Community", "Internships"],
    firstGenRelevance: "low",
    description:
      "Mentorship and employer matching program for students and recent grads with disabilities.",
    whyItMayFit:
      "May be relevant for disabled/neurodivergent students seeking mentors and employer connections.",
    reliability: "verified-live",
    badges: ["Mentorship", "Community"],
  },
  {
    id: "pro-bit",
    title: "Blacks in Technology (BIT)",
    lane: "professional",
    url: "https://www.blacksintechnology.net/",
    region: "National (serves Bay Area)",
    ageRange: ["18–24", "25+"],
    primaryCommunities: ["Black / African American"],
    secondaryCommunities: [],
    openToAll: false,
    interests: ["Computer Science", "AI / Data", "Cybersecurity"],
    supportTypes: ["Community", "Mentorship"],
    firstGenRelevance: "moderate",
    description: "Global community and media platform for Black people in technology.",
    whyItMayFit: "May be relevant for Black students seeking community and mentorship in tech.",
    reliability: "verified-live",
    badges: ["Community", "Mentorship"],
  },
  {
    id: "pro-epic",
    title: "EPIC (Empowering Pacific Islander Communities)",
    lane: "professional",
    url: "https://www.empoweredpi.org/",
    region: "National (serves Bay Area)",
    ageRange: ["18–24", "25+"],
    primaryCommunities: ["Pacific Islander"],
    secondaryCommunities: ["Underrepresented"],
    openToAll: false,
    interests: ["Unsure, help me explore", "Computer Science", "AI / Data"],
    supportTypes: ["Community", "Mentorship"],
    firstGenRelevance: "moderate",
    description:
      "Advocacy and leadership org for Native Hawaiian and Pacific Islander communities, incl. education.",
    whyItMayFit:
      "May be relevant for Pacific Islander students seeking community, leadership, and education support.",
    reliability: "verified-live",
    badges: ["Community"],
  },
  {
    id: "pro-maes",
    title: "MAES — Latinos in Science and Engineering",
    lane: "professional",
    url: "https://mymaes.org/",
    region: "National + university chapters (CA)",
    ageRange: ["16–17", "18–24", "25+"],
    primaryCommunities: ["Latinx / Hispanic"],
    secondaryCommunities: [],
    openToAll: false,
    interests: ["Engineering", "Computer Science", "AI / Data"],
    supportTypes: ["Scholarships", "Mentorship", "Community"],
    firstGenRelevance: "moderate",
    description:
      "Org developing Latinx leaders in engineering and science via chapters, scholarships, and a conference.",
    whyItMayFit:
      "May be relevant for Latinx students in engineering seeking community and scholarships.",
    reliability: "hand-curated",
    badges: ["Scholarship", "Mentorship", "Community"],
  },
];
